services:
  frontend:
    volumes:
      - ./frontend/src:/www/frontend/src
  backend:
    volumes:
      - ./backend/src:/www/backend/src
  builder:
    volumes:
      - ./builder/src:/www/builder/src
