# have to clean this whole env vars mess
services:
  frontend:
    build: 
      context: frontend
      args:
        - EXTREME_FRONTEND_PORT=${EXTREME_FRONTEND_PORT}
    container_name: extreme_frontend
    environment:
      - EXTREME_FRONTEND_PORT=${EXTREME_FRONTEND_PORT}
      - EXTREME_FRONTEND_MODE=${EXTREME_FRONTEND_MODE}
      - EXTREME_BACKEND_PORT=${EXTREME_BACKEND_PORT}
      - EXTREME_BACKEND_WS_PORT=${EXTREME_BACKEND_WS_PORT}
      - EXTREME_BACKEND_UDP_PORT=${EXTREME_BACKEND_UDP_PORT}
      - CLOUDFLARED_DOMAIN=${CLOUDFLARED_DOMAIN}
      - EXTREME_HOST_DOCKER=1 # docker check
  backend:
    build: 
      context: backend
      args:
        - EXTREME_BACKEND_PORT=${EXTREME_BACKEND_PORT}
    container_name: extreme_backend
    ports:
      - ${EXTREME_BACKEND_WS_PORT}:${EXTREME_BACKEND_WS_PORT}
      - ${EXTREME_BACKEND_UDP_PORT}:${EXTREME_BACKEND_UDP_PORT}/udp
    environment:
      - EXTREME_BACKEND_PORT=${EXTREME_BACKEND_PORT}
      - EXTREME_BACKEND_WS_PORT=${EXTREME_BACKEND_WS_PORT}
      - EXTREME_BACKEND_UDP_PORT=${EXTREME_BACKEND_UDP_PORT}
      - EXTREME_BUILDER_PORT=${EXTREME_BUILDER_PORT}
      - EXTREME_HOST_DOCKER=1 # docker check
  builder:
    build: 
      context: builder
      args:
        - EXTREME_BUILDER_PORT=${EXTREME_BUILDER_PORT}
    container_name: extreme_builder
    environment:
      - EXTREME_BUILDER_PORT=${EXTREME_BUILDER_PORT}
      - EXTREME_HOST_DOCKER=1 # docker check
  proxy:
    build:
      context: proxy
      args:
        - EXTREME_PROXY_PORT=${EXTREME_PROXY_PORT}
    container_name: extreme_proxy
    ports:
      - ${EXTREME_PROXY_PORT}:${EXTREME_PROXY_PORT}/tcp
      - ${EXTREME_PROXY_PORT}:${EXTREME_PROXY_PORT}/udp
    environment:
      - EXTREME_PROXY_PORT=${EXTREME_PROXY_PORT}
      - EXTREME_FRONTEND_PORT=${EXTREME_FRONTEND_PORT}
      - EXTREME_BACKEND_PORT=${EXTREME_BACKEND_PORT}
      - EXTREME_BACKEND_WS_PORT=${EXTREME_BACKEND_WS_PORT}
      - EXTREME_BACKEND_UDP_PORT=${EXTREME_BACKEND_UDP_PORT}
      - EXTREME_HOST_DOCKER=1 # docker check
    depends_on:
      - frontend
      - backend
      - builder